INCLUDE( FindPackageHandleStandardArgs )

SET(LLVM_CONFIG_NAMES llvm-config)
foreach(major RANGE 4 3)
  foreach(minor RANGE 9 0)
    list(APPEND LLVM_CONFIG_NAMES "llvm-config-${major}.${minor}")
  endforeach ()
endforeach ()
FIND_PROGRAM(LLVM_CONFIG NAMES ${LLVM_CONFIG_NAMES})

IF (LLVM_CONFIG)
  MESSAGE(STATUS "Found llvm-config: ${LLVM_CONFIG}")
ELSE()
  MESSAGE(FATAL_ERROR "llvm-config not found")
ENDIF()

EXECUTE_PROCESS(
  COMMAND ${LLVM_CONFIG} --libdir
  OUTPUT_VARIABLE LLVM_LIBDIR
  OUTPUT_STRIP_TRAILING_WHITESPACE
)

EXECUTE_PROCESS(
  COMMAND ${LLVM_CONFIG} --includedir
  OUTPUT_VARIABLE LLVM_INCLUDEDIR
  OUTPUT_STRIP_TRAILING_WHITESPACE
)

IF( "${LIBCLANG_DIR}" STREQUAL "" )
  SET( LIBCLANG_DIR "" CACHE STRING "An optional hint to a libclang directory" )
ENDIF()

FIND_PATH( LIBCLANG_INCLUDE_DIR
  clang-c/Index.h
  PATH ${LLVM_INCLUDEDIR}
)

FIND_LIBRARY( LIBCLANG_LIBRARY
  clang
  PATH ${LLVM_LIBDIR}
)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(
  LIBCLANG
  LIBCLANG_LIBRARY
  LIBCLANG_INCLUDE_DIR
)

IF( LIBCLANG_FOUND )
  SET( LIBCLANG_LIBRARIES    ${LIBCLANG_LIBRARY} )
  SET( LIBCLANG_INCLUDE_DIRS ${LIBCLANG_INCLUDE_DIR} )

  MARK_AS_ADVANCED(
    LIBCLANG_LIBRARY
    LIBCLANG_INCLUDE_DIR
  )
ELSE()
  MESSAGE(FATAL_ERROR "libclang not found")
ENDIF()
